# Use postgres/example user/password credentials
version: '3.9'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: depl
    ports:
      - '15432:5432'
